# Generated by Django 3.2.8 on 2021-11-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Batch')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Exam Pack Name')),
                ('details', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='exam_pack_cover_photos')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_pack_batch', to='Exam_Dashboard.batch')),
            ],
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('details', models.TextField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='exam_cover_photos')),
                ('total_mark', models.IntegerField(default=0)),
                ('pass_mark', models.IntegerField(default=0)),
                ('isRandomized', models.BooleanField(default=False, verbose_name='Randomization')),
                ('isSorted', models.BooleanField(default=False, verbose_name='Sorting')),
                ('isNegativeMarking', models.BooleanField(default=False, verbose_name='Negative Marking')),
                ('amount_per_mistake', models.IntegerField(default=0, verbose_name='Amount per mistake')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_batch', to='Exam_Dashboard.batch')),
                ('exam_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_pack', to='Exam_Dashboard.exampack')),
            ],
        ),
    ]
