# Generated by Django 3.2.8 on 2021-11-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamUtils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=100)),
                ('batch', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='exammodel',
            name='mark_per_question',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.TextField(max_length=1000)),
                ('question_img', models.ImageField(upload_to='question_bank')),
                ('exam_type', models.CharField(choices=[('type 1', 'type 1'), ('type 2', 'type 2')], max_length=30)),
                ('op_1', models.CharField(max_length=200, null=True)),
                ('op_2', models.CharField(max_length=200, null=True)),
                ('op_3', models.CharField(max_length=200, null=True)),
                ('op_4', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=200, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Dashboard.exammodel')),
            ],
        ),
    ]
