# Generated by Django 3.2.8 on 2021-11-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0004_auto_20211126_1018'),
        ('Exam_Dashboard', '0002_auto_20211125_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammodel',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='exammodel',
            name='level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exampack',
            name='level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examutils',
            name='board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='batch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exampack',
            name='batch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exam_type',
            field=models.CharField(choices=[('type 1', 'type 1'), ('type 2', 'type 2'), ('type 3', 'type 3')], max_length=30),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='question_bank'),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
