# Generated by Django 3.2.8 on 2021-11-22 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14, unique=True, verbose_name='Phone number')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('batch', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=500)),
                ('board', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
