# Generated by Django 3.2.8 on 2021-11-30 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=100)),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('board', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='01', max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('email', models.EmailField(blank=True, max_length=22, null=True, verbose_name='Student Mail')),
                ('level', models.CharField(max_length=30, verbose_name='Student level')),
                ('batch', models.CharField(max_length=40, verbose_name='Studnt Batch')),
                ('board', models.CharField(max_length=300, verbose_name='Student Board')),
                ('institution', models.CharField(max_length=100, verbose_name='Student Instituton')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
