# Generated by Django 3.2.8 on 2021-11-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0002_examtools_student_profile_student_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamTools',
            new_name='ExamTool',
        ),
    ]
