# Generated by Django 3.2.8 on 2021-11-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0002_alter_studentmodel_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='board',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Comilla', 'Comilla'), ('Jessore', 'Jessore'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Dinajpur', 'Dinajpur'), ('Madrasah', 'Madrasah')], max_length=100),
        ),
    ]
