# Generated by Django 3.2.8 on 2021-11-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0003_alter_studentmodel_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='board',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='batch',
            field=models.CharField(max_length=100),
        ),
    ]
